import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import ReduxProvider from "@/providers/reduxProvider";

const grotesk = localFont({
  src: "../fonts/ClashGrotesk-Variable.ttf",
});

export const metadata: Metadata = {
  title: "SENSA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/auth/sign-in">
      <html lang="en">
        <body className={`${grotesk.className} antialiased tracking-tight`}>
          <ReduxProvider>
            <Navbar />
            {children}
            <Toaster />
          </ReduxProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
